---
- name: Instala O Puppet Agent para o RHEL7
  yum:
    name: puppet-agent
    state: present 
  when: ansible_os_family == 'RedHat'

- name: Instala o Puppet Agent para o Ubuntu
  apt:
    name: puppet-agent
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Inicia o Puppet Agent
  service:
    name: puppet
    state: started
    enabled: true
