---
# tasks file for ambiente]
#
- name: Cria o conteiner blue
  docker_container:
    name: blue
    image: httpd
    state: started
    restart_policy: always
    volumes:
      - /blue:/usr/local/apache2/htdocs/

- name: Cria o conteiner green
  docker_container:
    name: green
    image: httpd
    state: started
    restart_policy: always
    volumes:
      - /green:/usr/local/apache2/htdocs/





